### ISSUE TITLE
minqlx ld_preload seems to break stdbuf

### ISSUE THREAD

**Issue by dpadgett** [MinoMino/minqlx#10]
my server.sh script has to launch the server:

stdbuf -oL -eL /home/${USER}/Steam/steamapps/common/Quake\ Live\ Dedicated\ Server/run_server_x64_minqlx.sh

i think setting the ld_preload like you are basically disabled the stdbuf rebuffering since that is also implemented via ld_preload.  seems you need to chain them together or something.

**Comment by MinoMino** [comment]
Oh, I see. I didn't think of that. Changing the export to `LD_PRELOAD=$LD_PRELOAD:./minqlx.so` probably fixes it. Give it a shot if you get the chance.

**Comment by MinoMino** [comment]
Addressed in v0.0.2.
