### ISSUE TITLE
multiple instances 

### ISSUE THREAD

**Issue by kikson112** [MinoMino/minqlx#102]
Hello

is there any posibility to make ex 2 or 3 instances or runned server in vps from same folder with different server.cfg ? is there any script ?

**Comment by em92** [comment]
Probably this is QLDS issue. The best way - to read this or ask there: https://steamcommunity.com/sharedfiles/filedetails/?id=542966946.
Section 2.
> A standard server or VPS can host many instances of Quake Live, so you may wish to run multiple servers
