### ISSUE TITLE
QLDS Ubuntu 20.4

### ISSUE THREAD

**Issue by dunderdotten** [MinoMino/minqlx#103]
Noob to Linux. Can someone please write down the exact steps to follow after doing a clean Ubuntu install?
I have tried so many times and its not working...

Steamcmd - installs fine
Redis-server, fine
Python3-dev, fine (even not clear on if i really need it???)

Minqlx - not so good... tar this, tar that, clone here, compile there.... so confusing to a user who does not use Linux and Git regularly.

Whatever i do i end up with errors. Like the step with cloneing minqlx and then "make" Error 127.
GCC error. and so on...
Trying to follow guides on here is like running around in a fishnet. 

I am not flaming on you guys who work hard with this, updates and so, but its really frustrating for a noob like myself :)

I wish there was a guide written so that my mother would understand it.

**Comment by dunderdotten** [comment]
update_minqlx.sh
[sudo] password for steam: 
Cloning into 'minqlx'...
remote: Enumerating objects: 1657, done.
remote: Total 1657 (delta 0), reused 0 (delta 0), pack-reused 1657
Receiving objects: 100% (1657/1657), 530.96 KiB | 613.00 KiB/s, done.
Resolving deltas: 100% (1031/1031), done.
gcc -m64 -fPIC -shared -std=gnu11 -I/usr/include/python3.8 -I/usr/include/python3.8 -DMINQLX_VERSION=\"v0.5.3-6-g90a344e-master\" -c HDE/hde64.c -o HDE/hde64.o
make: gcc: Command not found
make: *** [Makefile:60: HDE/hde64.o] Error 127
mv: cannot stat 'minqlx*': No such file or directory
update_minqlx.sh: line 11: cd: minqlx-plugins: No such file or directory
fatal: not a git repository (or any of the parent directories): .git

**Comment by dunderdotten** [comment]
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin 'plugin_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'essentials'...
[minqlx.load_plugin] INFO: Loading plugin 'motd'...
[minqlx.load_plugin] INFO: Loading plugin 'permission'...
[minqlx.load_plugin] INFO: Loading plugin 'ban'...
[minqlx.ban.log_exception] ERROR: Traceback (most recent call last):
[minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 361, in load_plugin
[minqlx.ban.log_exception] ERROR:     plugins[plugin] = plugin_class()
[minqlx.ban.log_exception] ERROR:   File "./minqlx-plugins/ban.py", line 35, in __init__
[minqlx.ban.log_exception] ERROR:     self.add_hook("game_start", self.handle_game_start)
[minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 113, in add_hook
[minqlx.ban.log_exception] ERROR:     minqlx.EVENT_DISPATCHERS[event].add_hook(self.name, handler, priority)
[minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 131, in add_hook
[minqlx.ban.log_exception] ERROR:     raise AssertionError("{} hook requires zmq_stats_enabled cvar to have nonzero value".format(self.name))
[minqlx.ban.log_exception] ERROR: AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 442, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 113, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.8/logging/__init__.py", line 2013, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 237, in handle_new_game
[minqlx.log_exception] ERROR:     minqlx.late_init()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 455, in late_init
[minqlx.log_exception] ERROR:     load_preset_plugins()
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 334, in load_preset_plugins
[minqlx.log_exception] ERROR:     load_plugin(p)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 361, in load_plugin
[minqlx.log_exception] ERROR:     plugins[plugin] = plugin_class()
[minqlx.log_exception] ERROR:   File "./minqlx-plugins/ban.py", line 35, in __init__
[minqlx.log_exception] ERROR:     self.add_hook("game_start", self.handle_game_start)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 113, in add_hook
[minqlx.log_exception] ERROR:     minqlx.EVENT_DISPATCHERS[event].add_hook(self.name, handler, priority)
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 131, in add_hook
[minqlx.log_exception] ERROR:     raise AssertionError("{} hook requires zmq_stats_enabled cvar to have nonzero value".format(self.name))
[minqlx.log_exception] ERROR: AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value

**Comment by em92** [comment]
Hi, @dunderdotten !
Seems like instructions are not so correct. You need to run `sudo apt-get -y install build-essential` before running `make`.
Also, in server.cfg set `zmq_stats_enabled` to non-zero value.

I will fix them later.

**Comment by em92** [comment]
Also, no idea what is "update_minqlx.sh"

**Comment by em92** [comment]
> Also, no idea what is "update_minqlx.sh"

Nevermind. Found in README https://gist.github.com/MinoMino/5a8c76da3edd953144ef

> I will fix them later.

Fixed via https://github.com/MinoMino/minqlx/commit/839de9aae5f5349bd019e3420065d57c4ed33373

> [minqlx.log_exception] ERROR: AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value

In server.cfg add "set zmq_stats_enable 1". Or update minqlx. Recent version includes https://github.com/MinoMino/minqlx/commit/5ff4abef95142f3e45f1722ce290dd74db802e50, so you don't have to enable zmq_stats via server.cfg

**Comment by em92** [comment]
Seem to be resolved. Closing.
