### ISSUE TITLE
help installing minqlx into a Windows QL server

### ISSUE THREAD

**Issue by veggy432** [MinoMino/minqlx#104]
hello, Im sorry to be so noob, I'd like to install this nice plugin to my server which is on a remote windows machine, I found the instructions are only for linux-based systems, I'm finding hard how to install the plugin under windows environment, anyone help?
also after installing I would like to enable the !elos command, (the server is already ranked in qlstats and matches get ranked but can't check the elos in-game)
cheerz

**Comment by em92** [comment]
Hi, @veggy432! Unfortunately you cannot use minqlx in Windows.
