### ISSUE TITLE
Add cvar to load every minqlx plugin available in the corresponding folder

### ISSUE THREAD

**Issue by garzfaust** [MinoMino/minqlx#105]
I would like to just load every plugin i have copied into the minqlx folder instead of additionally having to put them into the `qlx_plugins` cvar. Could you please implement a new cvar `qlx_autoloadPlugins` or something which if set to true just loads everything it finds?

**Comment by em92** [comment]
> Could you please implement a new cvar `qlx_autoloadPlugins` or something which if set to true just loads everything it finds?

Not planning to implement it. But you can do it via bash-scripting:
```bash
PLUGINS=`find minqlx-plugins/*.py | grep -v "__init__" | sed 's!.*/!!' | sed 's!\.py!!' | xargs | tr ' ' ', '`
./run_server_x64_minqlx.sh +set qlx_plugins $PLUGINS
```

**Comment by garzfaust** [comment]
At first, thank you for the script.

I tried to set minqlx cvars through the command line but it does not work. What i found is that i can only set minqlx cvars through the server.cfg or autoexec.cfg. Command line does not work. Have you tried it?

**Comment by em92** [comment]
> Command line does not work. Have you tried it?

Sorry, I didn't try it, when I wrote it. Edited the script above, removed "=" symbol.

**Comment by garzfaust** [comment]
I mean i have tested setting qlx_ cvars through the command line, without your script, and it does not work. I simply called `./run_server_x64_minqlx.sh +set qlx_enforceMappool 1` for example but it did not work. The map pool was not enforced. Setting it in the server.cfg or autoexec.cfg did work though. I think, setting qlx_ cvars through command line parameters does not work. Do you have a different experience?

**Comment by em92** [comment]
> I think, setting qlx_ cvars through command line parameters does not work. Do you have a different experience?

I checked qlx_plugin cvar. It works fine for me.
Screencast https://eugenemolotov.ru/static/minqlx-2021-04-26_22.21.25.mp4

**Comment by garzfaust** [comment]
Hey thank you very much for the screencast. I will check again if i can set the qlx_ cvars through command line parameters. I guess i made a mistake. If not, i will write again. ;>

Right now i am looking into the ZMQ stats events that QL is emitting. There are some cryptic properties i can't decipher. Is there any other channel i can talk to you? Were i can ask some questions from time to time?

**Comment by em92** [comment]
> Right now i am looking into the ZMQ stats events that QL is emitting. There are some cryptic properties i can't decipher.

Examples are here. https://github.com/PredatH0r/XonStat/tree/master/feeder/sample-data

> Is there any other channel i can talk to you? Were i can ask some questions from time to time?

If it is minqlx related, here are options:
1. create an issue here
2. ask in discord https://discord.gg/jxdcbzv or IRC `#qldedsrv` or `#minqlbot` on QuakeNet. Messages are mirrored to each channel and there are other people that could also help.

If quake live related, use 2nd option above.
