### ISSUE TITLE
should be > 15 (off-by-one error)

### ISSUE THREAD

**Issue by mgaertne** [MinoMino/minqlx#118]
I think there is an off-by-one error here:
https://github.com/MinoMino/minqlx/blob/c93838aa6f1b7b9648ac4d3ca45407867525a887/python_embed.c#L1000

16 weapons should be 0-15, so the check should be for >15 or >=16.

**Comment by em92** [comment]
Fixed in https://github.com/MinoMino/minqlx/commit/a020c39a59653957f4684e105701eecb4a7585c6
Thank you!
