### ISSUE TITLE
invalid ELF Header with release v0.0.3

### ISSUE THREAD

**Issue by mattiZed** [MinoMino/minqlx#12]
Tried to switch to minqlx v0.0.3 (downloaded release from github) this morning, console said it couldnt preload minqlx.so because of invalid ELF Header. File minqlx.so is only 30 KB, too. Compiled the minqlx.so myself, worked then!

**Comment by MinoMino** [comment]
Woah, I have absolutely no idea what might've happened there, but you're right. The tarball got corrupted somehow. New one uploaded. Thanks.
