### ISSUE TITLE
Update your readme

### ISSUE THREAD

**Issue by vandonsel** [MinoMino/minqlx#122]
Seriously. I am beyond pissed at how many circles i've been running in because your readme is so incredibly outdated

**Comment by em92** [comment]
Could you clarify what exactly is outdated?

**Comment by vandonsel** [comment]
steamcmd install an instance of quake live, follow your instructions for minqlx +plugins up to the point where you run the "sudo python3 -m pip install -r minqlx-plugins/requirements.txt" command and imagine how many people will have zero clue to do with that output. Had a nightmare of a time on both debian *and* arch, btw. I had to pull some wizardry with pyenv that took a lot of hand holding and the frustration was overall exhausting

**Comment by em92** [comment]
> Had a nightmare of a time on both debian

What version of debian?

**Comment by vandonsel** [comment]
12. I'm on arch now. The plugins load but can't seem to figure out how to make myself an admin/owner

**Comment by vandonsel** [comment]
I can't use debian 9 because the only denver vps provider seemingly in existence won't let me load custom isos...why is made for an ancient distro. Words cannot express how frustrating and obtuse both your minqlx and minqlx plugins instructions are. How was I supposed to know there's no = sign or a set prefix? Like this is awful dude

**Comment by em92** [comment]
> 12

Checked on isolated enviroment, here is what I get https://github.com/MinoMino/minqlx/issues/123
Is it what you got?

> How was I supposed to know there's no = sign or a set prefix? Like this is awful dude

I did not understand anything here. Is mention prefix is the same one that is commonly used as `PREFIX=/usr ./configure`?

**Comment by em92** [comment]
> The plugins load but can't seem to figure out how to make myself an admin/owner

`qlx_owner` is mention in README.

**Comment by vandonsel** [comment]
It's pretty vague now isn't it? It doesn't explicitly give an example like "set qlx_owner steamidhere", rather it says "Set the cvars by passing them as a command line argument or using server.cfg like you would with any other QLDS cvar." assuming the user has extensive knowledge in these plugins I've yet to get to work due to #123

**Comment by em92** [comment]
> It's pretty vague now isn't it?

No. It assumes, that you know what cvar is. If you don't know, then you can't configure QLDS with or without minqlx.

I any case, thank you for debian 12 error report.
