### ISSUE TITLE
Bug or?

### ISSUE THREAD

**Issue by OGtronTTV** [MinoMino/minqlx#128]
Got everything installed fine and working except when showing elo commands in game after any
map changes it takes about 8 seconds for it to show up.
After someone uses commands AFTER waiting that 8 seconds on the same map, things pop up
instantly for elo. 

Is this a bug or why would it be delayed on the server after every new map is loaded?

**Comment by em92** [comment]
"balance.py" plugin fetches ratings. It takes time. After fetching plugins stores them to cache.

This cache is invalidated, when starting new game. Starting new game is almost the same as new map loaded.

**Comment by em92** [comment]
Not a bug
