### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by BarelyMiSSeD** [MinoMino/minqlx#15]
I thought I had the bot installed correctly but after starting the server and connecting to it I get this on the console:
Client 0 connecting with 75 challenge ping
[minqlx.essentials.log_exception] ERROR: Traceback (most recent call last):
[minqlx.essentials.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.essentials.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.essentials.log_exception] ERROR:   File "./minqlx-plugins/essentials.py", line 104, in handle_player_connect
[minqlx.essentials.log_exception] ERROR:     self.update_player(player)
[minqlx.essentials.log_exception] ERROR:   File "./minqlx-plugins/essentials.py", line 652, in update_player
[minqlx.essentials.log_exception] ERROR:     if base_key not in self.db:
[minqlx.essentials.log_exception] ERROR:   File "minqlx.zip/minqlx/database.py", line 103, in __contains__
[minqlx.essentials.log_exception] ERROR:     return self.r.exists(key)
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 855, in exists
[minqlx.essentials.log_exception] ERROR:     return self.execute_command('EXISTS', name)
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
[minqlx.essentials.log_exception] ERROR:     connection.send_command(_args)
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
[minqlx.essentials.log_exception] ERROR:     self.send_packed_command(self.pack_command(_args))
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
[minqlx.essentials.log_exception] ERROR:     self.connect()
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 446, in connect
[minqlx.essentials.log_exception] ERROR:     self.on_connect()
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 514, in on_connect
[minqlx.essentials.log_exception] ERROR:     if nativestr(self.read_response()) != 'OK':
[minqlx.essentials.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 582, in read_response
[minqlx.essentials.log_exception] ERROR:     raise response
[minqlx.essentials.log_exception] ERROR: redis.exceptions.ResponseError: Client sent AUTH, but no password is set
broadcast: print "^1Barely^7Hit^4S^7^7 connected\n"
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 158, in handle_frame
[minqlx.log_exception] ERROR:     frame_tasks.run(blocking=False)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/sched.py", line 147, in run
[minqlx.log_exception] ERROR:     action(_argument, *_kwargs)
[minqlx.log_exception] ERROR:   File "./minqlx-plugins/motd.py", line 52, in handle_player_loaded
[minqlx.log_exception] ERROR:     motd = self.db[self.motd_key]
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/database.py", line 106, in __getitem__
[minqlx.log_exception] ERROR:     return self.r.get(key)
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 880, in get
[minqlx.log_exception] ERROR:     return self.execute_command('GET', name)
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 572, in execute_command
[minqlx.log_exception] ERROR:     connection.send_command(_args)
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
[minqlx.log_exception] ERROR:     self.send_packed_command(self.pack_command(_args))
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
[minqlx.log_exception] ERROR:     self.connect()
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 446, in connect
[minqlx.log_exception] ERROR:     self.on_connect()
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 514, in on_connect
[minqlx.log_exception] ERROR:     if nativestr(self.read_response()) != 'OK':
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 582, in read_response
[minqlx.log_exception] ERROR:     raise response
[minqlx.log_exception] ERROR: redis.exceptions.ResponseError: Client sent AUTH, but no password is set

I am not sure what it means, but the bot doesn't respond to any text.

I am new to Linux, though I have learned a lot the past couple of weeks, so any help would be appreciated.

I am running Ubuntu 14.04

**Comment by MinoMino** [comment]
You seem to have set qlx_redisPassword without setting a password in the 
Redis configuration.

**Comment by BarelyMiSSeD** [comment]
Thanks.. I put None in for the password instead of "".

Can you run the bot on multiple servers on the same computer?

**Comment by MinoMino** [comment]
Yup, it's designed with that in mind. Assuming you don't set 
qlx_redisDatabase to different values, all the servers will share the 
same database. So permissions, bans, etc. will all be the same across 
all your servers.

**Comment by BarelyMiSSeD** [comment]
I tried starting a second server using the same settings but it didn't load the bot. I will see if it is obvious and get back to you.

**Comment by BarelyMiSSeD** [comment]
It works.. Thanks Again
