### ISSUE TITLE
Motd newlines

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#19]
Would be good if all lines set with !addmotd will be showing to player, separated with newlines. Not sure why but it displays in a single line.

**Comment by MinoMino** [comment]
`\n` gets converted to newlines. That is, the two characters, and not an actual newline. In other words, you can do `!setmotd First line\nSecond line.`.

**Comment by Melodeiro** [comment]
Thanks, it seems to be good too.
