### ISSUE TITLE
!help content in database

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#20]
Would be great if there will be commands like !sethelp which will write info to database. So, after updating minqlx, changes in !help will not be canceled.

**Comment by MinoMino** [comment]
Changes in !help? Do you mean modifying the output? You generally shouldn't have a need to modify official plugins at all. If you want !help to do something else, simply make your own plugin, and add a command with `self.add_command("help", [...], priority=minqlx.PRI_HIGH)` and then return `minqlx.RET_STOP` in the handler to prevent the one in essentials from going off.

**Comment by Melodeiro** [comment]
Wow, you also solved my question about how to patch minqlx with my changes after updates! Thanks
