### ISSUE TITLE
Some hooks don't work

### ISSUE THREAD

**Issue by em92** [MinoMino/minqlx#23]
I have a plugin that adds hooks: http://pastebin.com/piKeLz5r
new_game, player_connect/disconnect - work.
game_end hook - doesn't work.

I have paid attention that if event name is not registered in register_handlers() function (_handlers.py) or/and event name is not in handlers array (python_embed.c), then hook with such event name won't work.

**Comment by MinoMino** [comment]
We talked on IRC. I'm going to assume you solved it, but just reopen it if that wasn't the case.
