### ISSUE TITLE
qlx_additionalPlugins

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#24]
Would be nice to have separate cvars for default plugins and for custom plugins eg qlx_additionalPlugins. And maybe cvar like qlx_disableDefaultPlugins but not sure if someone needs to disable something. So after updates we don't need to modify qlx_plugins to include new ones.

**Comment by MinoMino** [comment]
Yeah, I was actually considering something like this the other day. Although I think I might just add a special keyword to qlx_plugins instead. Something like `DEFAULT, my_plugin1, my_plugin2` making it load all the defaults plus whatever comes later.

**Comment by MinoMino** [comment]
Implemented in 4f063e237425f3cac1521df01acd0ae336ea6d65.
