### ISSUE TITLE
Motd header

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#25]
I am and one guy also wants a cvar or a command to change this: ^6**\* ^7Message of the Day ^6***
Or maybe i can somehow override it with my custom plugin?

**Comment by MinoMino** [comment]
Eh, I don't know about this one. I'd like to keep the number of cvars to a minimum and I don't know if this warrants a new one. I'll leave it open while I think about it for the time being.

**Comment by Melodeiro** [comment]
Is !setmotdheader not an option?
**Upd**: Or maybe just not hardcoding header will be a good idea. Just adding them to MOTDs of servers if someone wants to. And probably added to motd by default. Dont remember if default motd contains something

**Comment by MinoMino** [comment]
Went ahead and made it a cvar after all.
