### ISSUE TITLE
after 0.4.0 update from 0.3.1

### ISSUE THREAD

**Issue by kamilko** [MinoMino/minqlx#27]
Unable to run qlserver:
[minqlx] Searching for necessary functions...
[minqlx] Com_Printf: 0x421120
[minqlx] Cmd_AddCommand: 0x420970
[minqlx] ERROR: Unable to find Cmd_Args.
[minqlx] Cmd_Argv: 0x420620
[minqlx] Cmd_Argc: 0x4155d0
[minqlx] ERROR: Unable to find Cmd_TokenizeString.
[minqlx] Cbuf_ExecuteText: 0x420d30
[minqlx] Cvar_FindVar: 0x426100
[minqlx] Cvar_Get: 0x426b60
[minqlx] Cvar_GetLimit: 0x426750
[minqlx] Cvar_Set2: 0x4262e0
[minqlx] SV_SendServerCommand: 0x43dc10
[minqlx] SV_ExecuteClientCommand: 0x43a5a0
[minqlx] SV_Shutdown: 0x43d900
[minqlx] SV_Map_f: 0x437c70
[minqlx] SV_ClientEnterWorld: 0x43a4d0
[minqlx] SV_SetConfigstring: 0x43c370
[minqlx] SV_GetConfigstring: 0x43c550
[minqlx] SV_DropClient: 0x439490
[minqlx] Sys_SetModuleOffset: 0x452460
[minqlx] SV_SpawnServer: 0x43ccf0
[minqlx] Cmd_ExecuteString: 0x420ab0
[minqlx] Exiting.

**Comment by RobinHoutevelts** [comment]
There was a commit an hour ago.
Are you sure you are running the newest version?

_I'm just some guy that just stumbled upon here while figuring out how to host a QL server_

Edit: Pretty sure you just need to update to v0.4.0

**Comment by MinoMino** [comment]
Like @RobinHoutevelts said, sponge pushed a new update for QLDS that broke minqlx. v0.4.0 fixes this.

**Comment by RobinHoutevelts** [comment]
:+1:

**Comment by kamilko** [comment]
Before I send this issue I did:
- system update to be sure
- python3.5 modules update to be sure
- steamclient update
- click few times refresh button on minqlx/releases page

And file downloaded is maybe 5 minutes before I send issue.
md5 sums:
8a528573cdecece5454d7073ef1d6702  minqlx_v0.4.0.tar.gz
626248184bb83901d2743f26395b94da  minqlx.so

**Comment by MinoMino** [comment]
Make a file called `update_qlds` in your steamcmd directory with the following script:

```
@ShutdownOnFailedCommand 1
force_install_dir steamapps/common/qlds/
login anonymous
app_update 349090 validate
quit
```

And then run `steamcmd.sh +runscript update_qlds`. This assumes your server is installed in `steamapps/common/qlds/` of course, so edit that accordingly if that isn't the case.

**Comment by kamilko** [comment]
The steam update is ok.
But I downloaded once more v0.4.0.tar.gz (3minutes ago) and now minqlx.so has different md5sum (f401a22b88fa760e3726b3bd9739b66e) and server without problem.
It looks like ~30minutes ago was still wrong file in releases page.

**Comment by MinoMino** [comment]
Huh, that's weird. I only uploaded it once. But oh well, if it works now then that's cool.

**Comment by kamilko** [comment]
Probably I was faster than github CDN for my area ;)
