### ISSUE TITLE
Locking teams

### ISSUE THREAD

**Issue by Melodeiro** [MinoMino/minqlx#29]
Would be nice to see a commands for locking teams. Im trying to avoid using mod and admin privilegies. Something like !lock red, !lock all for perm level 2 i think would be nice.

**Comment by cstewart90** [comment]
I'm surprised there isn't !lock and !unlock commands already, I think it is just something Mino forgot to add to essentials. Would be really simple to add too, as all that is needed to do is self.lock(team) and self.unlock(team).
https://github.com/MinoMino/minqlx/blob/672ec2ecd91b009fc38b988c88d9c87775fbea82/python/minqlx/_plugin.py#L568

**Comment by MinoMino** [comment]
Yup, I simply forgot. I'll add it.

**Comment by MinoMino** [comment]
Done. Also needed a small change to the core (f3cc1396da5c251affe2e82a216c5b2c752925c8) to executing the lock/unlock method with no arguments, like you can with rcon.
