### ISSUE TITLE
Balance plugin cancels the round countdown on CA

### ISSUE THREAD

**Issue by tjone270** [MinoMino/minqlx#30]
In any CA game (might affect other modes), when players agree to a switch with !a, minqlx responds with "The switch will be executed at the start of the next round.", however at the start of the next round, the round countdown doesn't run.

**Comment by MinoMino** [comment]
Should've been fixed in MinoMino/minqlx-plugins@1b776f38ef5e77688a0cdc8086e3577cfded58ed. What version are you running?

**Comment by tjone270** [comment]
minqlx is at v0.4.0-1-g618f384-develop, with latest plugins from master.

**Comment by MinoMino** [comment]
That's why then.

Also, you should _always_ run master-master or develop-develop. You will run into issues sooner or later if you run a mix.

**Comment by tjone270** [comment]
I'm running a mix purely for the 'ping' player attribute, you said this was okay as the master was equal to develop at the time, excluding the lack of the 'ping' player attribute on master at the time. I've added that extra bit of code to the balance plugin, should be all fine now hopefully.

Thanks Mino :smiley:

**Comment by MinoMino** [comment]
Oh, right, I did indeed say that. That particular build should indeed be fine.
