### ISSUE TITLE
`ImportError: dynamic module does not define module export function (PyInit_minqlx)`

### ISSUE THREAD

**Issue by ozh** [MinoMino/minqlx#31]
Hello,

Not sure what I managed to break, but here's the error I have :

```
# ./launch.sh
[minqlx] Searching for necessary functions...
[minqlx] Com_Printf: 0x421120
[minqlx] Cmd_AddCommand: 0x420970
[minqlx] Cmd_Args: 0x420670
[minqlx] Cmd_Argv: 0x420620
[minqlx] Cmd_Argc: 0x4155d0
[minqlx] Cmd_TokenizeString: 0x4207f0
[minqlx] Cbuf_ExecuteText: 0x420d30
[minqlx] Cvar_FindVar: 0x426110
[minqlx] Cvar_Get: 0x426b70
[minqlx] Cvar_GetLimit: 0x426760
[minqlx] Cvar_Set2: 0x4262f0
[minqlx] SV_SendServerCommand: 0x43ddb0
[minqlx] SV_ExecuteClientCommand: 0x43a700
[minqlx] SV_Shutdown: 0x43daa0
[minqlx] SV_Map_f: 0x437c80
[minqlx] SV_ClientEnterWorld: 0x43a630
[minqlx] SV_SetConfigstring: 0x43c4f0
[minqlx] SV_GetConfigstring: 0x43c6d0
[minqlx] SV_DropClient: 0x4394a0
[minqlx] Sys_SetModuleOffset: 0x4527d0
[minqlx] SV_SpawnServer: 0x43ce70
[minqlx] Cmd_ExecuteString: 0x420ab0
[minqlx] Shared library loaded!
[minqlx] Hooking...
1066 linux-x64 Dec 17 2015 15:36:49
[minqlx] Initializing...
[minqlx] Initializing Python...
Traceback (most recent call last):
  File "<string>", line 6, in <module>
ImportError: dynamic module does not define module export function (PyInit_minqlx)
[minqlx] Python initialization failed: 2
```

I'm embarrassed to say I got it working for a couple of days, have broken something but cannot figure out what. Only thing I remember doing is tweaking a few `server.cfg` stuff and trying the [branding plugin](https://github.com/tjone270/Quake-Live/blob/master/minqlx-plugins/branding.py), which I've removed to be sure it wasn't the culprit.

Running latest qlds, minqlx and minqlx-plugins

Where should I look into?

**Comment by MinoMino** [comment]
You should have both `minqlx.so` and `minqlx.zip` in your QLDS installation directory, but I believe you're missing the latter.

**Comment by ozh** [comment]
OMG. Thought the .zip was an archive to be removed, I probably deleted it along with the .tar.gz ...

Thanks a bunch :) Merry Christmas!

**Comment by Gurumax** [comment]
Hello
After many days Brainfuck with Python.

I get this eror message.
/$ ./quakelive
[minqlx] Searching for necessary functions...
[minqlx] Com_Printf: 0x421120
[minqlx] Cmd_AddCommand: 0x420970
[minqlx] Cmd_Args: 0x420670
[minqlx] Cmd_Argv: 0x420620
[minqlx] Cmd_Argc: 0x4155d0
[minqlx] Cmd_TokenizeString: 0x4207f0
[minqlx] Cbuf_ExecuteText: 0x420d30
[minqlx] Cvar_FindVar: 0x426110
[minqlx] Cvar_Get: 0x426b70
[minqlx] Cvar_GetLimit: 0x426760
[minqlx] Cvar_Set2: 0x4262f0
[minqlx] SV_SendServerCommand: 0x43ddb0
[minqlx] SV_ExecuteClientCommand: 0x43a700
[minqlx] SV_Shutdown: 0x43daa0
[minqlx] SV_Map_f: 0x437c80
[minqlx] SV_ClientEnterWorld: 0x43a630
[minqlx] SV_SetConfigstring: 0x43c4f0
[minqlx] SV_GetConfigstring: 0x43c6d0
[minqlx] SV_DropClient: 0x4394a0
[minqlx] Sys_SetModuleOffset: 0x4527d0
[minqlx] SV_SpawnServer: 0x43ce70
[minqlx] Cmd_ExecuteString: 0x420ab0
[minqlx] Shared library loaded!
[minqlx] Hooking...
1066 linux-x64 Dec 17 2015 15:36:49
[minqlx] Initializing...
[minqlx] Initializing Python...
[minqlx] Python initialization failed: 2

Only error what i get by install of python was by the last step.
sudo python3.5 -m pip install -r minqlx-plugins/requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'minqlx-plugins/requirements.txt'

Maybe the prob comes from there ?

Big Thanks for any Help !
greets

**Comment by MinoMino** [comment]
Hi,

If that step failed, then it certainly won't work. It failed to find 
requirements.txt, which leads me to believe you might've changed the 
working directory in between steps there. Your requirements.txt should 
be in qlds/minqlx-plugins, so you're going to have to repeat that step 
and correct the path you pass to it after the -r part.

Mino

**Comment by Gurumax** [comment]
Hello
Big Thanks!! 
For help me solve my problem.
Server runs now with minqlx ;-)
3Days and Nights Brainfucking have a end.
Or not, now must check this plugins ....

Greets

**Comment by Gurumax** [comment]
Hi
elo dont work with °Attack & Defend° Mod ?
greets

**Comment by MinoMino** [comment]
Unfortunately qlstats.net doesn't, which is what I use. I'm not the guy 
who runs that site, that's PredatH0r. You could try asking him to add 
it, I guess.

Mino

**Comment by Gurumax** [comment]
ok, then i ask PredatH0r
thx
