### ISSUE TITLE
ubuntu 14.04 32 bit ....

### ISSUE THREAD

**Issue by fb-rain** [MinoMino/minqlx#37]
ERROR: ld.so: object './minqlx.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

where can I find the 32bit version?

BTW: Failed to build with source code.

gcc -m32 -fPIC -shared -std=gnu11 -I/usr/include/python3.5m -I/usr/include/python3.5m  -Wno-unused-result -Wsign-compare -Wunreachable-code -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMINQLX_VERSION=\"v0.4.5-0-gf4afa59-master\" -c HDE/hde32.c -o HDE/hde32.o
gcc -m32 -fPIC -shared -std=gnu11 -I/usr/include/python3.5m -I/usr/include/python3.5m  -Wno-unused-result -Wsign-compare -Wunreachable-code -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMINQLX_VERSION=\"v0.4.5-0-gf4afa59-master\" -c dllmain.c -o dllmain.o
dllmain.c: In function 鈥楽earchFunctions鈥

```
                                        dllmain.c:138:76: error: 鈥楶TRN_CMD_TOKENIZESTRING鈥undeclared (first use in this function)
```

  Cmd_TokenizeString = (Cmd_TokenizeString_ptr)PatternSearchModule(&module, PTRN_CMD_TOKENIZESTRING, MASK_CMD_TOKENIZESTRING);
                                                                            ^
dllmain.c:138:76: note: each undeclared identifier is reported only once for each function it appears in

**Comment by Melodeiro** [comment]
> At the moment it only supports the x64 build of the server

Readme says.

**Comment by em92** [comment]
> where can I find the 32bit version?

Build this from source.
https://github.com/em92/minqlx/tree/x86-support

Tested ffa server on my debian 8.6 32bit. Looks fine.

**Comment by em92** [comment]
Added 32bit support: https://github.com/MinoMino/minqlx/releases/tag/v0.5.2
