### ISSUE TITLE
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher

### ISSUE THREAD

**Issue by AsphyxEvents** [MinoMino/minqlx#38]
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin ''...
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR: 
[minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
[minqlx.log_exception] ERROR: 
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 397, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 107, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/**init**.py", line 1144, in getLogger
[minqlx.log_exception] ERROR:     if not isinstance(name, str):
[minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set
´

any ideas ?

**Comment by MinoMino** [comment]
Looks like your qlx_plugins cvar is set to something invalid. Make sure 
it doesn't have any trailing commas.

**Comment by AsphyxEvents** [comment]
ah lol, yeah thank you , it was a comma behind the last plugin : afk,"

thx for your fast reply and your nice tool!
