### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by notallmighty** [MinoMino/minqlx#41]
I don't know where to start. I am getting these errors, my guess was I haven't placed cvars properly, but they are placed. So what do i do?

 ./run_server_x64_minqlx.sh
[minqlx] Searching for necessary functions...
[minqlx] Com_Printf: 0x421170
[minqlx] Cmd_AddCommand: 0x4209c0
[minqlx] ERROR: Unable to find Cmd_Args.
[minqlx] Cmd_Argv: 0x420670
[minqlx] Cmd_Argc: 0x415620
[minqlx] ERROR: Unable to find Cmd_ArgsFrom.
[minqlx] ERROR: Unable to find Cmd_TokenizeString.
[minqlx] Cbuf_ExecuteText: 0x420d80
[minqlx] Cvar_FindVar: 0x426160
[minqlx] Cvar_Get: 0x426bc0
[minqlx] Cvar_GetLimit: 0x4267b0
[minqlx] Cvar_Set2: 0x426340
[minqlx] SV_SendServerCommand: 0x43de10
[minqlx] SV_ExecuteClientCommand: 0x43a760
[minqlx] SV_Shutdown: 0x43db00
[minqlx] SV_Map_f: 0x437cd0
[minqlx] SV_ClientEnterWorld: 0x43a690
[minqlx] SV_SetConfigstring: 0x43c550
[minqlx] SV_GetConfigstring: 0x43c730
[minqlx] SV_DropClient: 0x4394f0
[minqlx] Sys_SetModuleOffset: 0x452bd0
[minqlx] va: 0x435b80
[minqlx] Exiting.

Thanks,

**Comment by MinoMino** [comment]
Make 100% sure you're running both the latest QLDS _and_ minqlx. Some of 
the recent updates to QLDS forced me to change some of the patterns used 
for the function searching, rendering them incompatible unless they're 
both the latest.

**Comment by notallmighty** [comment]
I was sure i have updated minqlx, but I have not. Now it runs. Thanks
