### ISSUE TITLE
fun.py 

### ISSUE THREAD

**Issue by notallmighty** [MinoMino/minqlx#48]
I extended yakumo's version of your's plugin fun.py to put it in my server, but an issue happens. Some sounds won't play. I use sound samples according to your advice, mono 16bit .ogg files. I created workshop pack, and added it as needed to server.cfg: set qlx_workshopReferences "=workshopnumber=". Than a some of packed sounds work some will not.
 I am even not sure where to seek the problem. Could be just only this, that script is too long? Any advises welcome. Plugin self is below.
[fun (2).txt](https://github.com/MinoMino/minqlx/files/516179/fun.2.txt)

**Comment by dsverdlo** [comment]
Look for errors in your minqlx.log (located in the fs_homepath directory). If you added a lot of commands, chances are that you misspelled or forgot some regex variables and an error causes the sounds not to be played.

**Comment by tjone270** [comment]
I make sound files in Audacity that 100% of the time work, the specifications are 22050Hz, single-channel audio track, and I usually turn the gain up just a small fraction. You can split a stereo track into a mono track with the small arrow menu on the left-upper part of the track info. Save the file as an Ogg Vorbis file.

**Comment by notallmighty** [comment]
I also used Audacity to prepare it. 
I will check thing with probing rate, and rework all of them to 22,05khz. A Strange thing with it, is that some of them are in 22khz, they work, some 44khz  play, and some 44khz don't. Thus, will see how it goes. All them 16bit mono *(single-channel).ogg
I will let u know, what i found.

**Comment by notallmighty** [comment]
It worked, converting to 22050Hz works, also i found a miss-typed path. Thank you for pointing me to a  right direction.
