### ISSUE TITLE
help erro starting

### ISSUE THREAD

**Issue by cheros13** [MinoMino/minqlx#53]
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin 'plugin_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'sounds'...
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 397, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 107, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
[minqlx.log_exception] ERROR:     if not isinstance(name, str):
[minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set
Hitch warning: 1806 msec frame time
zmq stats and rcon passwords updated

**Comment by dsverdlo** [comment]
Make sure sounds.py is located in the plugins folder. The loader says it cannot find it.

**Comment by MinoMino** [comment]
>[minqlx.load_plugin] INFO: **Loading plugin 'sounds'...**
>...
>[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: **No such plugin exists.**

In other words, the plugin `sounds` doesn't exist.

**Comment by cheros13** [comment]
[minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
[minqlx] PyObject_CallFunction() returned NULL.
[minqlx.log_exception] ERROR: minqlx._core.PluginLoadError: No such plugin exists.
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 397, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 107, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
[minqlx.log_exception] ERROR:     if not isinstance(name, str):
[minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set

**Comment by cheros13** [comment]
:(

**Comment by MinoMino** [comment]
🐧

**Comment by cheros13** [comment]
ubuntu 12.04

**Comment by MinoMino** [comment]
Windows 8.1

**Comment by cheros13** [comment]
There is no solution to these errors ?

**Comment by MinoMino** [comment]
There is. You're trying to load a plugin that doesn't exist. Without any more insight, I can't help you. For every plugin in `qlx_plugins`, you must have a matching plugin with the .py extension in `minqlx-plugins`.

**Comment by cheros13** [comment]
[minqlx.late_init] INFO: Loading preset plugins...
[minqlx.load_plugin] INFO: Loading plugin 'silence'...
[minqlx.load_plugin] INFO: Loading plugin 'workshop'...
[minqlx.load_plugin] INFO: Loading plugin 'plugin_manager'...
[minqlx.load_plugin] INFO: Loading plugin 'essentials'...
[minqlx.load_plugin] INFO: Loading plugin 'permission'...
[minqlx.load_plugin] INFO: Loading plugin 'log'...
[minqlx.load_plugin] INFO: Loading plugin 'ban'...
[minqlx.load_plugin] INFO: Loading plugin 'motd'...
[minqlx.load_plugin] INFO: Loading plugin 'names'...
[minqlx.load_plugin] INFO: Loading plugin 'clan'...
[minqlx.late_init] INFO: We're good to go!
[minqlx.handle_new_game] WARNING: Some events will not work because ZMQ stats is not enabled. Launch the server with "zmq_stats_enable 1"
Hitch warning: 1447 msec frame time
zmq stats and rcon passwords updated

**Comment by cheros13** [comment]
it was ?

**Comment by MinoMino** [comment]
>it was ?

No idea what you mean with that, but since you seem to have removed the non-existent plugin, it now works.

**Comment by cheros13** [comment]
Does not appear in the server list :(

**Comment by cheros13** [comment]
Where I get a server.cfg minqlx

Set auto spec

All commands

**Comment by cheros13** [comment]
set qlx_elo_limit_max "1600"
set qlx_autospec_minplayers "2"
set qlx_autospec_maxplayers "99"
set qlx_plugins "balance, plugin_manager, essentials, motd, permission, ban, silence, clan, log, workshop, names"
set qlx_owner "76561198074897398"
set qlx_leaverBan "1"
set qlx_workshopReferences "1" 
set qlx_leaverBanThreshold "0.75"
set qlx_leaverBanWarnThreshold "0.80"
set qlx_leaverBanMinimumGames "15"
set qlx_balanceAuto "1"
set qlx_balanceUseLocal "0"
set qlx_balanceMinimumSuggestionDiff "30"
set qlx_motdHeader "^7==^2 ^1A CAIXA DE QUAKE ^7==^2 CLAN ARENA ^7==^3 minqlx + gametrack ^7==^4 brasil ^7==^2"
set qlx_motdSound "sound/vo_evil/holy_shit.ogg"
set qlx_serverBrandName "^1A CAIXA^7 Clan Arena"
set qlx_serverBrandTopField "^7Running ^2minqlx^7 and ^2qlstats.net^7"
set qlx_serverBrandBottomField "^7Have ^1fun^7, play well, don't ^3whine^7"
set qlx_votepass "1"
set qlx_enforceMappool "1"

set fraglimit 0
set timelimit 0
set teamsize 8
set roundlimit 10

set fraglimit 0
set timelimit 0
set teamsize 8
set roundlimit 10

**Comment by cheros13** [comment]
that's right ?

**Comment by MinoMino** [comment]
I'm not sure what you mean. If you want features from custom plugins, you need to get them and put them in `steamcmd/steamapps/common/qlds/minqlx-plugins` and then add them to `qlx_plugins` like it seems you were trying to earlier.

**Comment by cheros13** [comment]
I want to enable the sounds plugin

http://steamcommunity.com/sharedfiles/filedetails/?id=620087103&searchtext=sound

Do not touch

**Comment by MinoMino** [comment]
Just follow the instructions there. And if you want them to be triggered by chat, replace `fun.py` with the one by Yakumo in the pastebin there.

EDIT: Oh, and for whatever reason, you've set `qlx_workshopReferences` to `1`, when the instructions there clearly tell you to set it to `620087103`.

**Comment by cheros13** [comment]
I did not understand this part
Yakumo in the pastebin there.

**Comment by MinoMino** [comment]
[This Pastebin](http://pastebin.com/raw/PF7WKGdh) has a modified `fun.py` made by Yakumo. Replace the contents of your current one with that one.

**Comment by cheros13** [comment]
Typing this command the sound comes out

Sound sound / funnysounds / SpaceUnicorn.ogg

The chat does not sound.. 
Already substitutes fun.py

:(

**Comment by MinoMino** [comment]
I don't know. I can probably tell you what's wrong if you pastebin all your stuff. Like your config, workshop.txt, fun.py and the log of the latest run.

**Comment by cheros13** [comment]
server.cfg redis erro help

[minqlx.log_exception] ERROR:     return self.execute_command('SADD', name, *values)
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 578, in execute_command
[minqlx.log_exception] ERROR:     connection.send_command(*args)
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 563, in send_command
[minqlx.log_exception] ERROR:     self.send_packed_command(self.pack_command(*args))
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
[minqlx.log_exception] ERROR:     self.connect()
[minqlx.log_exception] ERROR:   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
[minqlx.log_exception] ERROR:     raise ConnectionError(self._error_message(e))
[minqlx.log_exception] ERROR: redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
[minqlx.log_exception] ERROR:
[minqlx.log_exception] ERROR: Traceback (most recent call last):
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 397, in handle_console_print
[minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
[minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 107, in get_logger
[minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
[minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
[minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
[minqlx.log_exception] ERROR:     if not isinstance(name, str):
[minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set

**Comment by cheros13** [comment]
server.cfg add set qlx_redisAddress "redis"

start server erro :(

**Comment by MinoMino** [comment]
Oh god.

>qlx_redisAddress "redis"

Where'd you even get that from? Just leave it as the default if you don't know what it does.

**Comment by jwinett** [comment]
> ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

It looks like you have set qlx_redisAddress to "redis" and the host name does not resolve to an IP address.  

> qlx_redisAddress: The address to the Redis database. Can be a path if qlx_redisUnixSocket is "1".
> Default: 127.0.0.1
> qlx_redisDatabase: The Redis database number.
> Default: 0
> qlx_redisUnixSocket: A boolean that determines whether or not qlx_redisAddress is a path to a UNIX socket.
> Default: 0
> qlx_redisPassword: The password to the Redis server, if any.
> Default: None
