### ISSUE TITLE
[Question] Ability to manage server from outside quakelive client

### ISSUE THREAD

**Issue by MPogoda** [MinoMino/minqlx#57]
Hi!

Is there a way or maybe a plan to enable managing qlx server (with qlx commands) from outside quakelive client?

**Comment by MinoMino** [comment]
`qlx` is an RCON command that allows you to run minqlx commands, so you can connect to the server remotely using ZMQ from anywhere and manage it. Alternatively, you can use the IRC plugin.

**Comment by MPogoda** [comment]
Welp, missed it ._.

Thanks :)
