### ISSUE TITLE
elo ratings 1337

### ISSUE THREAD

**Issue by alpiua** [MinoMino/minqlx#59]
Hello.
I dont know, if i made something wrong, but all players who came to my server see !elo rating exactly "1337" for all of them. Even if they have something abour near 2000 elo points.

minqlx part of config is looks like:

set qlx_plugins "plugin_manager, essentials, motd, permission, ban, silence, clan, names, log, workshop, balance, branding, changemap, pingspec, clanspinner, autorestart, custom_votes"

set qlx_balanceUrl "qlstats.net"
set qlx_balanceApi "elo_b"
set qlx_protectedPerm "3"
set qlx_defaultMapToChangeTo "bloodrun"
set qlx_defaultMapFactoryToChangeTo "duel"
set qlx_pingSpecSecondsBetweenChecks "30"
set qlx_pingSpecMaxPing "120"
set qlx_rulesetLocked "1"
set qlx_disablePlayerRemoval "0"
set qlx_disableCvarVoting "1"
set qlx_cvarVotePermissionRequired "3"

**Comment by em92** [comment]
> set qlx_balanceApi "elo_b"

I guess you should change it to:

> set qlx_balanceApi "elo"
