### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by notallmighty** [MinoMino/minqlx#60]
I got an idea, i would certainly welcome, if there is a plugin that balance game, and it moves players between servers. For eg.
If I have 2 servers for example chocolate starfish 1 and 2 and is 1 full, plugin  would move the 5 toplisted players onto second server after the game is done. Than on server 2 it would move 4 or less low ranking players to the server 1. I have seen such thing in cs,  and worked there well.  Thank you for reading boss.

**Comment by MinoMino** [comment]
Unfortunately, there's no way to force the client to connect to another server. CS and other HL-based games have a server command that allows it to run any console command on the client. QL had that at some point too, but since it can be abused by server admins, sponge removed it before the Steam-only update went official.

**Comment by notallmighty** [comment]
Hehe, (...) what a pity. I remember that funny callvotes and stuff. Adming powah! Also is a pity is that Sponge thinks that he rules all the quake and he does all the work we do in the meantime...ehh  What about cvar max_players during the gameplay.?? maybe dynami temporary expand of server could do a job?

**Comment by MinoMino** [comment]
Well, to be fair, it could be abused pretty heavily. Having your settings screwed up and your config wiped for just joining a server for a second, for instance, would not be cool.

As for the last part, changing cvars during gameplay is fine, but assuming you mean `sv_maxClients`, then that's one of the cvars that need a map change before working if I'm not mistaken.
