### ISSUE TITLE
Run command/script on event?

### ISSUE THREAD

**Issue by lsabalo** [MinoMino/minqlx#61]
Hi... I was wondering if there is a way to run a command or a script triggered by an event, like a flag captured, a kill, etc...
Are you aware of any plugin or something that could do that?
Thanks!

**Comment by em92** [comment]
>script triggered by an event, like a flag captured, a kill, etc...

Examples, how to hook kill event: https://github.com/dsverdlo/minqlx-plugins/search?utf8=%E2%9C%93&q=death
afaik, it is not able to hook flag captured events in current (0.5.0) version.
