### ISSUE TITLE
[feature] introduce /topshots like in OSP

### ISSUE THREAD

**Issue by DimitarChristoff** [MinoMino/minqlx#64]
as per title, how hard would that be?

**Comment by em92** [comment]
AFAIK, it would require to make a new function or structure in minqlx core that will use https://github.com/MinoMino/minqlx/blob/dfe4b110e9150616411f8e2ee185fbb78e3357e2/quake_common.h#L1022-L1027
Don't know if zmq information provides such info. If yes - you just need to write own plugin for minqlx without modifying minqlx core.
Try to ask in #minqlbot irc channel at QuakeNet. Maybe someone will implement it.

**Comment by dsverdlo** [comment]
Could you elaborate on what "topshots like in OSP" is? Perhaps give an example of an idea that you had in mind?

**Comment by notallmighty** [comment]
I bet, he would like have a qlstats, than on this based top frag list, that appears using !topshots

**Comment by DimitarChristoff** [comment]
pretty much iterates over weapons stats and outputs current highest accuracy per weapon ranked in the game in % and hits/fired. 

see https://ioquake3.org/files/ioq3/osp/Docs/osp-q3-History.txt

relevant notes about this:
```
- Add: bottomshots command (analogous to topshots)
- Change: sort topshots <weap> by accuracy percent
- Add: "topshots" that gives the best player accuracy for all weapons.  If followed
       with a weapon's abbreviation (i.e. RL for Rocket Launcher), this command will
       show the accuracy for all players of the specified weapon (10 shot minimum to
       be included in the list). (thanks arqy :) )
       Supported abbreviations: MG, SG, LG, GL, RL, RG, PG, BFG
```

I am trying to see the output for this but it was pretty much like:

```
wep   player                 %                   
=================================================
LG    foobar                 46%         460/1000
RG    EK.BOB                 66%            12/18
RL    foobar                 20%             5/20
```
Since it's verbose, this was a console command as /topshots per personal use and it was auto-dumped at the end of each map. 

Bottomshots was added for laughs later

**Comment by dsverdlo** [comment]
Hmm as em92 stated, I also think getting this type of information would require some changes to the minqlx core.
