### ISSUE TITLE
minqlx incorrectly interpreting the cvars

### ISSUE THREAD

**Issue by tamas36** [MinoMino/minqlx#65]
If I write something invalid (not starting with _//_) in the config file behind the cvar's closing _"_ character, the minqlx ignores the mentioned closing character and appends the cvar.

For example:

**minqlx.cfg:**
```
set qlx_plugins "plugin_manager, essentials, etc" # invalid comment
set qlx_commandPrefix "!" // valid comment
```

**in-game:**
```
qlx_plugins "plugin_manager, essentials, etc # invalid comment"
qlx_commandPrefix "!"
```

At the _qlx_plugins_ line minqlx should not append the cvar with the _# invalid comment_ text.

**Comment by em92** [comment]
That's not a minqlx issue. That's general cvar parsing issue in qlds. Contact id Software.

**Comment by dsverdlo** [comment]
So you are saying that stuff doesn't work when you don't use the correct commentary character?

**Comment by tjone270** [comment]
@em92 is correct. This is not minqlx related.
