### ISSUE TITLE
it seems steamid doesn't works for command "!ban "

### ISSUE THREAD

**Issue by DOM-prova** [MinoMino/minqlx#66]
hi, as in subject, i can't set ban using steamid... 
eg= !ban 546877426 30 days troll
i am admin level 2, do you have same isssue about that?

**Comment by em92** [comment]
Ban by client_id instead. Too big chance to have a typo, when writing steam_id.

>eg= !ban 546877426 30 days troll

546877426 doesn't look like valid steam_id

**Comment by DOM-prova** [comment]
user was not in server, so only steamid i can use

the user have this (working) URL in steam:

http://steamcommunity.com/id/546877426/

but qlstat.net has this steam number (dunno why)

http://steamcommunity.com/profiles/76561198121895550/

if yuou click on steam id you are redirected to this working url above

anyway i test the command with both numbers and nothing happen

do you ever try to use command !ban with steamid? please test it with a 
valid number, i fear it doesnt work as well

regards


Il 23/04/2017 18:37, Eugene Molotov ha scritto:
