### ISSUE TITLE
Multiple instances on one machine - loading different config.cfg's?

### ISSUE THREAD

**Issue by mattiZed** [MinoMino/minqlx#7]
Is it possible to launch multiple instances of qlds with minqlx using different config.cfg's? What about putting the config files in the corresponding fs_homepaths? will that work, or does minqlx always look for its config in qlds/baseq3/minqlx?

People might run different gamemodes like CA, FFA and DUEL and wouldn't want the same settings to apply for all. e. g. min/max teamsize, no leaver-banning on FFA etc.

This might also solve issue #3.

**Comment by MinoMino** [comment]
Addressed in v0.0.2.
