### ISSUE TITLE
On our server we have crashes everyday  , any solutions?

### ISSUE THREAD

**Issue by jasmineclon** [MinoMino/minqlx#76]
we  have this problem that our server crashes once in 24hours same as in this post :
https://github.com/MinoMino/minqlx/issues/40  any solution would be appreciated ty :)

(02:51:09) [DEBUG @ minqlx.handle_console_print] ----------------------
(02:51:09) [DEBUG @ minqlx.handle_console_print] 23613 files in pk3 files
(02:51:09) [DEBUG @ minqlx.handle_console_print] Loading dll file qagame
(02:51:09) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) found dllEntry at 0x7ff8ccb980b0
(02:51:09) [DEBUG @ minqlx.handle_console_print] Sys_LoadDll(qagame) succeeded!
(02:51:09) [DEBUG @ minqlx.handle_console_print] Sys_SetModuleOffset: qagame 0x7FF8CCB980B0
(02:51:09) [DEBUG @ minqlx.handle_console_print] ------- Game Initialization -------
(02:51:09) [DEBUG @ minqlx.handle_console_print] gamename: baseqz
(02:51:09) [DEBUG @ minqlx.handle_console_print] gamedate: Apr 11 2016
(02:51:09) [DEBUG @ minqlx.handle_console_print] initializing access list...
(02:51:09) [DEBUG @ minqlx.handle_console_print] loaded 16 steam ids into the access list
(02:51:09) [DEBUG @ minqlx.handle_console_print] Not logging to disk.
(02:51:09) [DEBUG @ minqlx.handle_console_print] 0 teams with 0 entities
(02:51:09) [DEBUG @ minqlx.handle_console_print] 24 items registered
(02:51:09) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(02:51:09) [DEBUG @ minqlx.handle_console_print] -----------------------------------
(02:51:09) [DEBUG @ minqlx.dispatch] map('cliffside', 'freeze')
(02:51:09) [DEBUG @ minqlx.dispatch] new_game()
(02:51:16) [DEBUG @ minqlx.handle_console_print] qagame: 0x7FF8CCB980B0
cgame: 0x0
ui: 0x0
[0x452936]
[0x7FF8D77CE340]
[0x7FF8D6A1CA03]
[0x7FF8D6ADA235]
[0x7FF8CCB990AC]
[0x7FF8CCB7B0D6]
[0x7FF8CCB86755]
[0x43ACC0]
[0x4250CC]
[0x42522D]
[0x450E39]
[0x4078EE]
[0x7FF8D69F2EC5]
0x4079F9 [DEBUG @ minqlx.handle_console_print] version: 1068 linux-x64 Mar 4 2016 19:27:22
(02:51:16) [DEBUG @ minqlx.handle_console_print] g_version: 1068 linux-x64 Apr 11 2016 15:28:26
(02:51:16) [DEBUG @ minqlx.handle_console_print] ----- Server Shutdown -----
(02:51:16) [DEBUG @ minqlx.handle_console_print] ==== ShutdownGame ====
(02:51:16) [DEBUG @ minqlx.handle_console_print] ---------------------------
(02:51:29) [INFO @ minqlx._configure_logger] ============================= minqlx run @ 2016-05-05 02:51:29.353146 =============================
(02:51:29) [INFO @ minqlx.late_init] Loading preset plugins...

**Comment by em92** [comment]
> version: 1068 linux-x64 Mar 4 2016 19:27:22

Latest version is 1069. June 7, 2016
https://steamcommunity.com/games/282440/announcements/detail/876328108049672536

But updating to latest qlds won't help. Use supervisor to automatically restart crashed server.

**Comment by jasmineclon** [comment]
our crash is same as the one I posted :) we have updated Linux also quakelive :) what can be the reason starting crash after updates ?

**Comment by em92** [comment]
> what can be the reason starting crash after updates ?

I don't know. Will make some instructions later in discord/irc channel that will help to figure out what is going on.

**Comment by jasmineclon** [comment]
i read a lot forums some say it might be from plugins not compatible with update :) some say write code for qlds based on ioquake3`s,

**Comment by jasmineclon** [comment]
what can we do to stop server crashing ?

**Comment by em92** [comment]
> some say write code for qlds based on ioquake3`s,

That was me. But this is just an option.

> what can we do to stop server crashing ?

Don't know. Will as I said earlier

> I don't know. Will make some instructions later in discord/irc channel that will help to figure out what is going on.

**Comment by jasmineclon** [comment]
ty :)) u give me answers on support and here :)

**Comment by jasmineclon** [comment]
``I don't know. Will make some instructions later in discord/irc channel that will help to figure out what is going on``
thank you that will be so great :))))

**Comment by notallmighty** [comment]
Had this been sorted? I assume you need to extend hunkmegs buffer. Altho it is not difficult to adjust cvars in game, problematic can be somehow doing it before our oldschoolish qlds goes into protected mode. So the best way ist to inject cvar before app runs at all. For example using bash wrapper script, and adding cvar just after qlds is called to run (similarly to windows .bat) +set com_hunkMegs (large like 256).

**Comment by jasmineclon** [comment]
Sorry late answer we will try  hunkmegs 256 ty :)

**Comment by em92** [comment]
Copy from discord channel:
```
[10:51] eugene: @Jasmine what is up with your issue? Have you solved it?
[01:22] Jasmine: @eugene yes ty we have solved :))))
```

**Comment by li-nt** [comment]
This issue is still ongoing for us and has been since 2016.  @jasmineclon I'd like to know what else you did to resolve this because my hunkmegs has always been 1024 or greater and this happens at least once per day.
