### ISSUE TITLE
team_switch event not working for bots? 

### ISSUE THREAD

**Issue by githubflub** [MinoMino/minqlx#85]
1. Bot connects. 
2. Bot tries to join. 
3. team_switch_attempt's player arg has the expected player: Bones
4. team_switch's player arg does not have the expected player: Bones. Instead, it has a non-bot player.

How to fix?

**Comment by em92** [comment]
Sorry for the delay. Currently busy last days.

Will reproduce and debug it later, when I have time

**Comment by githubflub** [comment]
No problem! I appreciate that you would still work on this even in 2019. This bug was just making it harder to test my own plugins with bots. However, I was able to get the plugin to work anyway, so there's no rush to fix this bug!

**Comment by em92** [comment]
Fixed in commit above. Haven't released new version of minqlx yet, but if you still need it, replace your minqlx.zip file with this one.
[minqlx.zip](https://github.com/MinoMino/minqlx/files/3563770/minqlx.zip)

Thanks for report!
