### ISSUE TITLE
Improvement: BSP entities available via minqlx

### ISSUE THREAD

**Issue by tjone270** [MinoMino/minqlx#87]
Hi all,

I'm curious to see if people have interest in having the ability to read the BSP entities directly through minqlx. 

I've written a library that allows me to extract entity information (type, class, origin etc) from a BSP file, and a corresponding plugin that allows minqlx to assemble the path to the currently loaded .pk3, read out the BSP internally and read the entity lump. 

If there's interest in this, I'll put the effort in to open a pull request and implement in minqlx core.

**Comment by em92** [comment]
Hey Thomas! Long time no see

> I'm curious to see if people have interest in having the ability to read the BSP entities directly through minqlx.

Not interesting in reading BSP entities programatically itself, but I am interested how can you read any file from baseq3's pk3s and other workshop pk3s by given filename.

> I'll put the effort in to open a pull request and implement in minqlx core.

If this can be done as plugin without changing minqlx core, maybe we won't touch core?

**Comment by tjone270** [comment]
Hey, yes indeed - it's been a while.

This is how my current code does it (the module zipfile has a lot to do with it, but the tricky part is getting the path to the BSP assembled): https://gist.github.com/tjone270/9cbfc4abdcda6340064b8b440c24beec

The `bsp.py` is the module that pulls data from the BSP itself, the `ra3maps.py` minqlx plugin primarily assembles the path to the currently loaded .pk3/bsp. 

This could be done without changing the core, however it would mean either adding this class to the bottom of each plugin that wanted to use it. If there was a bug fix for example, everyone would have to re-paste this class. If there was interest from the community, it would probably be best to centralise the ability within minqlx itself, and "minqlxify"/embed the bsp.py file in the core. It's up to you however.

**Comment by em92** [comment]
> This could be done without changing the core, however it would mean either adding this class to the bottom of each plugin that wanted to use it.

Tried myself. Putting bsp.py to qlds directory is enough to load it in plugin, so no need to add it's body to bottom of plugin. At least if you run via `run_server_x64_minqlx.sh` which changes current directory to qlds one, so python knows where to find it.

**Comment by em92** [comment]
I guess issue can be closed.
