### ISSUE TITLE
Fresh install doesn't work

### ISSUE THREAD

**Issue by npendlington** [MinoMino/minqlx#91]
Hopefully this project is just alive enough still! :)
I know the docs recommend Ubuntu 16.10 but I presumed that it would be sensible to try the latest and greatest. So my attempt is on Ubuntu 18.04.3 LTS.

Steamcmd and the qlds installed fine following instructions online and I have a vanilla server up and running without any headaches. When I switch my launch script to use the _minqlx variants of the server run script, I get the dependency error for python 3.4:

./qzeroded.x86: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

Interestingly the x64 version can't find python 3.5:

./qzeroded.x64: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

I installed python3.4 from an old repo thinking that could be the issue, but I still get the same errors.

~$ whereis python3
python3: /usr/bin/python3.4m /usr/bin/python3.6m /usr/bin/python3 /usr/bin/python3.6 /usr/bin/python3.4 /usr/bin/python3.6-config /usr/bin/python3.6m-config /usr/lib/python3 /usr/lib/python3.6 /usr/lib/python3.4 /usr/lib/python3.7 /etc/python3 /etc/python3.6 /etc/python3.4 /usr/local/lib/python3.6 /usr/local/lib/python3.4 /usr/include/python3.6m /usr/include/python3.6 /usr/share/python3 /usr/share/man/man1/python3.1.gz

**Comment by tjone270** [comment]
Hey there,

Have you installed python-dev?

Please excuse brevity as this message was sent from my iPhone

**Comment by npendlington** [comment]
No problem at all, appreciate the response. Linux is a little out of my comfort zone, so it could be something easily diagnosed to someone with better understanding.

I didn't have python-dev installed (the instructions ask for you to run `sudo apt-get -y install python3 python3-dev`), but I've since also installed python-dev (which installed a bunch of packages- see below) and unfortunately I get the same error still.

`The following NEW packages will be installed:`
`  libpython-dev libpython-stdlib libpython2.7 libpython2.7-dev`
`  libpython2.7-minimal libpython2.7-stdlib python python-dev python-minimal`
`  python2.7 python2.7-dev python2.7-minimal`
`0 upgraded, 12 newly installed, 0 to remove and 36 not upgraded.`

**Comment by em92** [comment]
You should install python3-dev and take away these lines: https://github.com/MinoMino/minqlx/blob/master/python/minqlx/_core.py#L39-L43

And then, recompile

**Comment by em92** [comment]
Or you can just use compiled version for python 3.6
http://eugenemolotov.ru/static/minqlx.x64.so

**Comment by npendlington** [comment]
@em92 Awesome - thanks. Being a developer, I chose the (slightly) harder option and pulled the repo and compiled myself. More to prove the point than anything else, but it worked a treat and now I can launch the x64 server!
Getting an error about the ban plugin, but that's completely separate and I'll tackle that later.

Thanks for the assistance everyone! Hopefully this will help someone else having the same issue.

**Comment by ghost** [comment]
I wanted to re-open this given that the newest release of minqlx states support for Python 3.6. I get the following error on a fresh install:

`./qzeroded.x64: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory`

Trying to avoid installing older versions of Python from random PPAs, is there a way around this at all?

**Comment by em92** [comment]
@id0827502 compile minqlx from source. https://github.com/MinoMino/minqlx/blob/master/README.md#compiling

As for now, it is the only option. Somewhen I will change install instructions.

**Comment by em92** [comment]
Fixed install instructions. https://github.com/MinoMino/minqlx/commit/65b63f01063c96ef7fa6f6528d98d4a68513e54e
