### ISSUE TITLE
Infinite error messages

### ISSUE THREAD

**Issue by agkr234** [MinoMino/minqlx#93]
> [minqlx.late_init] INFO: Loading preset plugins...
> [minqlx.load_plugin] INFO: Loading plugin 'plugin_manager'...
> [minqlx.load_plugin] INFO: Loading plugin 'essentials'...
> [minqlx.load_plugin] INFO: Loading plugin 'motd'...
> [minqlx.motd.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.motd.log_exception] ERROR:   File "./minqlx/_core.py", line 361, in load_plugin
> [minqlx.motd.log_exception] ERROR:     plugins[plugin] = plugin_class()
> [minqlx.motd.log_exception] ERROR:   File "./minqlx-plugins/motd.py", line 43, in __init__
> [minqlx.motd.log_exception] ERROR:     self.db.sadd(MOTD_SET_KEY, self.home)
> [minqlx.motd.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.motd.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.motd.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.motd.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.motd.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.motd.log_exception] ERROR:     return getattr(self.r, attr)
> 
Same error messages go on...
> 
> [minqlx.motd.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.motd.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.motd.log_exception] ERROR: RecursionError: maximum recursion depth exceeded
> [minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
> [minqlx] PyObject_CallFunction() returned NULL.
> [minqlx.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.log_exception] ERROR:   File "./minqlx/_core.py", line 361, in load_plugin
> [minqlx.log_exception] ERROR:     plugins[plugin] = plugin_class()
> [minqlx.log_exception] ERROR:   File "./minqlx-plugins/motd.py", line 43, in __init__
> [minqlx.log_exception] ERROR:     self.db.sadd(MOTD_SET_KEY, self.home)
> [minqlx.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.log_exception] ERROR:     return getattr(self.r, attr)
> 
Same error messages go on...
> 
> [minqlx.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.log_exception] ERROR:   File "./minqlx/database.py", line 147, in __getattr__
> [minqlx.log_exception] ERROR:     return getattr(self.r, attr)
> [minqlx.log_exception] ERROR: RecursionError: maximum recursion depth exceeded
> [minqlx.log_exception] ERROR: 
> [minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
> [minqlx.log_exception] ERROR: 
> [minqlx.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.log_exception] ERROR:   File "./minqlx/_handlers.py", line 442, in handle_console_print
> [minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
> [minqlx.log_exception] ERROR:   File "./minqlx/_core.py", line 113, in get_logger
> [minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
> [minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
> [minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
> [minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
> [minqlx.log_exception] ERROR:     if not isinstance(name, str):
> [minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set

It occurs whether qlx_plugins is set or not in server.cfg
minqlx-plugins folder is in the right directory.

**Comment by tjone270** [comment]
Looks like there’s something wrong with your Redis instance. Ensure it’s working properly and is correctly configured before trying again.

**Comment by em92** [comment]
What does `pip freeze` return?

**Comment by agkr234** [comment]
@tjone270, @em92 
Thanks for your prompt responses.

I'm not sure what Redis instance is since I'm new to linux or server things, but I will try it.

And here's what pip freeze returns

> apturl==0.5.2
> beautifulsoup4==4.4.1
> blinker==1.3
> Brlapi==0.6.4
> chardet==2.3.0
> checkbox-support==0.22
> command-not-found==0.3
> cryptography==1.2.3
> defer==1.0.6
> feedparser==5.1.3
> guacamole==0.9.2
> hiredis==1.0.0
> html5lib==0.999
> httplib2==0.9.1
> idna==2.0
> Jinja2==2.8
> language-selector==0.1
> louis==2.6.4
> lxml==3.5.0
> Mako==1.0.3
> MarkupSafe==0.23
> oauthlib==1.0.3
> onboard==1.2.0
> padme==1.1.1
> pexpect==4.0.1
> Pillow==3.1.2
> plainbox==0.25
> ptyprocess==0.5
> pyasn1==0.1.9
> pycups==1.9.73
> pycurl==7.43.0
> pygobject==3.20.0
> PyJWT==1.3.0
> pyparsing==2.0.3
> python-apt==1.1.0b1+ubuntu0.16.4.5
> python-debian==0.1.27
> python-systemd==231
> pyxdg==0.25
> pyzmq==17.1.3
> redis==2.10.6
> reportlab==3.3.0
> requests==2.9.1
> sessioninstaller==0.0.0
> six==1.10.0
> system-service==0.3
> ubuntu-drivers-common==0.0.0
> ufw==0.35
> unattended-upgrades==0.1
> unity-scope-calculator==0.1
> unity-scope-chromiumbookmarks==0.1
> unity-scope-colourlovers==0.1
> unity-scope-devhelp==0.1
> unity-scope-firefoxbookmarks==0.1
> unity-scope-gdrive==0.7
> unity-scope-manpages==0.1
> unity-scope-openclipart==0.1
> unity-scope-texdoc==0.1
> unity-scope-tomboy==0.1
> unity-scope-virtualbox==0.1
> unity-scope-yelp==0.1
> unity-scope-zotero==0.1
> urllib3==1.13.1
> usb-creator==0.3.0
> xdiagnose==3.8.4.1
> xkit==0.0.0
> XlsxWriter==0.7.3
> 

Actually, I'm trying to launch minqlx server on VirtualBox, but i don't think using VirtualBox matters because I succeeded on another machine with VirtualBox.

**Comment by em92** [comment]
In [instructions](https://github.com/MinoMino/minqlx/blob/master/README.md) there is line:

> Now you should get Redis and Git, which will be used by minqlx's plugins:

Have you done it?
Also:
- Which OS is installed in virtualbox?
- After installing redis, what does `netstat -tulpn` return?

**Comment by agkr234** [comment]
@em92 
Yes, this is what it returned when I typed `sudo apt-get -y install redis-server git`

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> git is already the newest version (1:2.7.4-0ubuntu1.6).
> redis-server is already the newest version (2:3.0.6-1ubuntu0.4).
> The following package was automatically installed and is no longer required:
>   snapd-login-service
> Use 'sudo apt autoremove' to remove it.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


・Which OS is installed in virtualbox?
Ubuntu 16.04 LTS, and it's 64bit version.

・After installing redis, what does netstat -tulpn return?
It says,

> (Not all processes could be identified, non-owned process info
>  will not be shown, you would have to be root to see it all.)
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -               
> tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
> tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
> tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
> udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -               
> udp        0      0 0.0.0.0:36290           0.0.0.0:*                           -               
> udp        0      0 0.0.0.0:631             0.0.0.0:*                           -               
> udp        0      0 0.0.0.0:54258           0.0.0.0:*                           -               
> udp        0      0 127.0.1.1:53            0.0.0.0:*                           -               
> udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
> udp6       0      0 :::5353                 :::*                                -               
> udp6       0      0 :::32838                :::*                                -               
>

**Comment by agkr234** [comment]
I installed another ubuntu on VirtualBox and it launched minqlx server without any problem.
Maybe I installed something bad during the setup and it made the ubuntu unable to launch the server.
Sorry for having bothered you.
