### ISSUE TITLE
Quake Live many players problems 

### ISSUE THREAD

**Issue by vonskunck** [MinoMino/minqlx#98]
Hi am hosting 6 QL servers now(on two different physical servers and ISP). But after passing aprox 22 players am/everyone getting "Unknown client game command 0:" in the quake live console and if you press tab to view the scoreboard all the DM i zero. Normally the DM is back at the end of the round so less of a problem. Normally when this occurs all clients is getting disconnected when the map changes. Am running ubuntu 16.04.7 LTS and 18.04.4 LTS and same problem.
ubuntu 18 = Python 3.5.6
ubuntu 16 = Python 3.5.2
am running the 64bit version of "**run_server_x64_minqlx.sh**"
Anyone knows what to do ? 
Best Regards /las at skunck.se

**Comment by em92** [comment]
Hi, @vonskunck !

> But after passing aprox 22 players am/everyone getting "Unknown client game command 0:" in the quake live console

I don't know, why it happens. Try to ask @SyncError or @sponge in official quake live discord channel.

> if you press tab to view the scoreboard all the DM i zero

It is done intentionally in qlds. When there too many players on game server, damage values and some other things are not sent to players. Why? Scoreboard values for all players must fit 1024 chars. So when it does not fit, those values are not set or filled with zeros to fit. It cannot be solved just via minqlx, you have to rewrite both client and server code which is impossible at the moment.

> Normally when this occurs all clients is getting disconnected when the map changes

There is a workaround plugin which probably fixes it. https://pastebin.com/xMq3uW8G
Ping @mgaertne.

**Comment by vonskunck** [comment]
Hi Eugene !

Thanks alot for the help, but could you tell me what to do with that pice of code ? where should i'll paste it ?
Cant find any readme file.

Best Regards /las @ skunck.se

________________________________
Från: Eugene Molotov <notifications@github.com>
Skickat: den 6 november 2020 09:25
Till: MinoMino/minqlx <minqlx@noreply.github.com>
Kopia: vonskunck <von_skunck@hotmail.com>; Mention <mention@noreply.github.com>
Ämne: Re: [MinoMino/minqlx] Quake Live many players problems (#98)


Hi, @vonskunck<https://github.com/vonskunck> !

But after passing aprox 22 players am/everyone getting "Unknown client game command 0:" in the quake live console

I don't know, why it happens. Try to ask @SyncError<https://github.com/SyncError> or @sponge<https://github.com/sponge> in official quake live discord channel.

if you press tab to view the scoreboard all the DM i zero

It is done intentionally in qlds. When there too many players on game server, damage values and some other things are not sent to players. Why? Scoreboard values for all players must fit 1024 chars. So when it does not fit, those values are not set or filled with zeros to fit. It cannot be solved just via minqlx, you have to rewrite both client and server code which is impossible at the moment.

Normally when this occurs all clients is getting disconnected when the map changes

There is a workaround plugin which probably fixes it. https://pastebin.com/xMq3uW8G
Ping @mgaertne<https://github.com/mgaertne>.

**Comment by em92** [comment]
This is plugin.
```
cd minqlx-plugins
curl https://pastebin.com/raw/xMq3uW8G > overflow_fix.py
```
Then load it via qlx_plugins cvar. Or load it temporarly via `!load overflow_fix` ingame.

Forgot to mention, that con of this plugin - you won't have damage given/taken and other values in endgame scoreboard.

**Comment by vonskunck** [comment]
Super thanks !

Have a nice weekend.

Best Regards /las @ skunck.se

________________________________
Från: Eugene Molotov <notifications@github.com>
Skickat: den 6 november 2020 10:23
Till: MinoMino/minqlx <minqlx@noreply.github.com>
Kopia: vonskunck <von_skunck@hotmail.com>; Mention <mention@noreply.github.com>
Ämne: Re: [MinoMino/minqlx] Quake Live many players problems (#98)


This is plugin.

cd minqlx-plugins
curl https://pastebin.com/raw/xMq3uW8G > overflow_fix.py


Then load it via qlx_plugins cvar. Or load it temporarly via !load overflow_fix ingame.

Forgot to mention, that con of this plugin - you won't have damage given/taken and other values in endgame scoreboard.
