### ISSUE TITLE
problem loading plugin ban.py

### ISSUE THREAD

**Issue by kikson112** [MinoMino/minqlx#99]
Hello 

i try add mino plugins but im stuck there

> [minqlx.late_init] INFO: Loading preset plugins...
> [minqlx.load_plugin] INFO: Loading plugin 'plugin_manager'...
> [minqlx.load_plugin] INFO: Loading plugin 'essentials'...
> [minqlx.load_plugin] INFO: Loading plugin 'motd'...
> [minqlx.load_plugin] INFO: Loading plugin 'permission'...
> [minqlx.load_plugin] INFO: Loading plugin 'ban'...
> [minqlx.ban.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 361, in load_plugin
> [minqlx.ban.log_exception] ERROR:     plugins[plugin] = plugin_class()
> [minqlx.ban.log_exception] ERROR:   File "./minqlx-plugins/ban.py", line 35, in __init__
> [minqlx.ban.log_exception] ERROR:     self.add_hook("game_start", self.handle_game_start)
> [minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 113, in add_hook
> [minqlx.ban.log_exception] ERROR:     minqlx.EVENT_DISPATCHERS[event].add_hook(self.name, handler, priority)
> [minqlx.ban.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 131, in add_hook
> [minqlx.ban.log_exception] ERROR:     raise AssertionError("{} hook requires zmq_stats_enabled cvar to have nonzero value".format(self.name))
> [minqlx.ban.log_exception] ERROR: AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value
> [minqlx] ERROR @ python_dispatchers.c:164 in NewGameDispatcher:
> [minqlx] PyObject_CallFunction() returned NULL.
> [minqlx.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 361, in load_plugin
> [minqlx.log_exception] ERROR:     plugins[plugin] = plugin_class()
> [minqlx.log_exception] ERROR:   File "./minqlx-plugins/ban.py", line 35, in __init__
> [minqlx.log_exception] ERROR:     self.add_hook("game_start", self.handle_game_start)
> [minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 113, in add_hook
> [minqlx.log_exception] ERROR:     minqlx.EVENT_DISPATCHERS[event].add_hook(self.name, handler, priority)
> [minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 131, in add_hook
> [minqlx.log_exception] ERROR:     raise AssertionError("{} hook requires zmq_stats_enabled cvar to have nonzero value".format(self.name))
> [minqlx.log_exception] ERROR: AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value
> [minqlx.log_exception] ERROR:
> [minqlx.log_exception] ERROR: During handling of the above exception, another exception occurred:
> [minqlx.log_exception] ERROR:
> [minqlx.log_exception] ERROR: Traceback (most recent call last):
> [minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_handlers.py", line 442, in handle_console_print
> [minqlx.log_exception] ERROR:     minqlx.get_logger().debug(text.rstrip("\n"))
> [minqlx.log_exception] ERROR:   File "minqlx.zip/minqlx/_core.py", line 113, in get_logger
> [minqlx.log_exception] ERROR:     return logging.getLogger("minqlx")
> [minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
> [minqlx.log_exception] ERROR:     return Logger.manager.getLogger(name)
> [minqlx.log_exception] ERROR:   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
> [minqlx.log_exception] ERROR:     if not isinstance(name, str):
> [minqlx.log_exception] ERROR: SystemError: <built-in function isinstance> returned a result with an error set
> Hitch warning: 928 msec frame time
> zmq stats and rcon passwords updated
> Hitch warning: 3592 msec frame time

any idea how to solve ? 

thanks in advance

**Comment by em92** [comment]
Hi, @kikson112 !
Traceback says itself how to fix:
```
AssertionError: game_start hook requires zmq_stats_enabled cvar to have nonzero value
```
set zmq_stats_enable's value to 1 in server.cfg as example.

**Comment by kikson112** [comment]
ya my bad i forgot to remove // in this line all works thx
